### ISSUE TITLE
Sound Issue

### ISSUE THREAD

**Issue by Stonepia** [AngelDTF/OpenParsec#24]
Hello, May I ask how should I set the sound? I used the VB Cable as a virtual sound output, but I could not get sound from the OpenParsec side. I also tried connecting to the host from other device, and it does have sound. May I ask is there any method I could offer you a log, or how could I set up the sound device?

**Comment by AngelDTF** [comment]
I myself use VB Cable and had sound issues in the past before starting this project. Make sure the sample rate of Cable Output is set to either 44100hz or 48000hz, and if that doesn't work, try changing it to 16 bit as well.
