### ISSUE TITLE
Can’t login 

### ISSUE THREAD

**Issue by soteris24** [AngelDTF/OpenParsec#27]
I cant login for some reason. :/ 

I put my email and password, i press login but it does nothing, only says loading for a second and then it goes away.

Im in ipad 6th gen ios 16.3.1

**Comment by AngelDTF** [comment]
Are you using the [latest version of the IPA](https://github.com/AngelDTF/OpenParsec/releases/download/nightly/OpenParsec.ipa)?

**Comment by soteris24** [comment]
Oh im sorry, the link you gave me worked im an idiot :D
