### ISSUE TITLE
When I build it on Xcode 14.3 it gives me 2 errors 1. Command SwiftCompile failed with a nonzero exit code. 2. /Users/myprivateusernamegoeshere/Documents/OpenParsec/OpenParsec/MainView.swift:2:8 No such module 'ParsecSDK'

### ISSUE THREAD

**Issue by Fgksjaaagkjsf** [AngelDTF/OpenParsec#5]

**Comment by Fgksjaaagkjsf** [comment]
<img width="248" alt="Screenshot 2023-04-10 at 9 02 42 am" src="https://user-images.githubusercontent.com/119998034/230800494-91fbfadb-0b09-46ae-9bad-85ff8e0ebbb8.png">

**Comment by Fgksjaaagkjsf** [comment]
could you just provide an ipa for me pls?

**Comment by oOJohn6Oo** [comment]
> could you just provide an ipa for me pls?

You need to download the Parsec-SDK and make a link to solve the error. Full instructions 👉 #1 

I built it yesterday, it's  a simple app currently only support login and connect.

I can upload an ipa if it is allowed.

**Comment by oOJohn6Oo** [comment]
[Parsec.zip](https://github.com/AngelDTF/OpenParsec/files/11199992/Zip.archive.zip)

**Comment by Fgksjaaagkjsf** [comment]
Thank you. 👍
