### ISSUE TITLE
Error connecting to Host (code 100) when connecting to iMac

### ISSUE THREAD

**Issue by Redeemer2k** [AngelDTF/OpenParsec#9]
Thank you for your work to launch a parsec client for iPadOS! I sideloaded the latest IPA (from the Dropbox-Link) using sideloadly, but when connecting to my iMac 2020 running macOS i get the following error: „Error connecting to host (code 100). What does „code 100“ mean? I cannot find it in the Parsec knowledgebase… the only available codes there are either 99 or 101, but no 100… :-/ Thanks for your help!

**Comment by nomi-san** [comment]
The error code 100 is "CONNECT_WRN_UNCONFIRMED".
It might indicate issues related to the exchange of packets between peers (your client-host). It could imply that the expected response or acknowledgment from the peer has not been received, suggesting an incomplete or unreliable communication.

```c
  CONNECT_WRN_APPROVAL      = 6,       ///< 6
  CONNECT_WRN_DECLINED      = 8,       ///< 8
  CONNECT_WRN_CANCELED      = 9,       ///< 9
  CONNECT_WRN_NO_ROOM       = 11,      ///< 11
  CONNECT_WRN_PEER_GONE     = 99,      ///< 99
  CONNECT_WRN_UNCONFIRMED   = 100,     ///< 100
  CONNECT_WRN_NO_PERMISSION = 112,     ///< 112
```

**Comment by Redeemer2k** [comment]
Hi! Sorry for the late reply… the firewall on my mac was causing the problem… although i put parsec in the exceptions it would only work after turning off and on the firewall… :-D
